[package]
name = "nostd"
authors = ["Nicola Coretti <nico.coretti@gmail.com>"]
edition = "2021"
version = "0.1.0"
readme = "README.md"
license = "MIT OR Apache-2.0"

[lib]
name = "nostd"
path = "src/lib.rs"

